services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-demo}"
    image: demo-work-template
    platform: linux/amd64
    container_name: demo-work-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-demo}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-demo}/.config/gcloud
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    init: true


