services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models
    networks:
      - genai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # open-webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   ports:
  #     - "3000:8080"
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #   volumes:
  #     - ./backend/data:/app/backend/data
  #   networks:
  #     - genai-network
  app: 
    build: . # Build the application from current directory using the Dockerfile
    ports:
      - "5000:5000" # Expose the application using port 5000
    volumes:
      - .:/app # Mount the current directory to /app in the container
    networks:
      - genai-network
    environment:
      - CURL_CA_BUNDLE=""
      - REQUESTS_CA_BUNDLE=""
    depends_on:
      - ollama
networks:
  genai-network:
    name: genai-network
    #external: true