apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Server
  qps: 2000
  burst: 4000
  cacheSize: 20000
- type: Namespace
  qps: 300
  burst: 600
  cacheSize: 3000